Hosts :
  R1 :
    - IP : '172.16.0.100'
    - SSH_LOGIN : 'Admin'
    - SSH_PASS : 'Admin'
    - ENABEL_PASS : 'Admin'
    - INTERFACE : 'f0/0'
    - VLANS_IP : 
      - 10 : '192.168.10.2'
      - 20 : '192.168.20.100'
      - 30 : '192.168.30.250'
      - 80 : '192.168.80.200'
  R2 :
    - IP : '172.16.0.110'
    - SSH_LOGIN : 'Admin'
    - SSH_PASS : 'Admin'
    - ENABEL_PASS : 'Admin'
    - INTERFACE : 'f0/0'
    - VLANS_IP : 
      - 11 : '192.168.11.2'
      - 12 : '192.168.12.100'
      - 13 : '192.168.13.250'
      - 14 : '192.168.14.200'
  R4 :
    - IP : '172.16.0.200'
    - SSH_LOGIN : 'Admin'
    - SSH_PASS : 'Admin'
    - ENABEL_PASS : 'Admin'
    - INTERFACE : 'f0/0'
    - VLANS_IP : 
      - 50 : '192.168.50.2'
      - 60 : '192.168.60.100'
      - 70 : '192.168.70.250'
      - 90 : '192.168.90.200'