---
DATABASE_CONFIG :
  DATABASE_NAME:
    # Ip Address here
    IP : 127.0.0.1
    # This Database will use Default Port 3306
    
  DATABASE_NAME02:
    # Ip Address here
    IP : 192.168.1.10
    # Different Port
    Port : 4444

Default:
  Port : 3306
